
resnet18:
 full_name: resnet18
 ckp_path: resnet18/resnet18.pth.tar

# resnet152:
#  full_name: resnet152 
#  ckp_path: None 

# densenet121: 
#  full_name: densenet121
#  ckp_path: None

# convnextb:
#  full_name: convnext_base
#  ckpt_path: None

# repvgg:
#  full_name: repvgg_b1
#  ckpt_path: None 

# vgg19:
#  full_name: vgg19
#  ckp_path: vgg16/vgg16_bn_cifar10.pth.tar

resnet50:
 full_name: resnet50
 ckp_path: resnet50/resnet50.pth.tar

inc_v3:
 full_name: inception_v3
 ckp_path: inc_v3/inception_v3.pth.tar

vit_t:
 full_name: vit_tiny_patch16_224
 ckp_path: vit_t/vit_tiny.pth.tar

# deit_b:
#  full_name: deit_base_patch16_224
#  ckp_path: deit_b/deit_base.pth.tar

deit_t:
 full_name: deit_tiny_patch16_224
 ckp_path: deit_t/deit_tiny.pth.tar

swin_t:
 full_name: swin_tiny_patch4_window7_224
 ckp_path: None


